apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    role: client
spec:
  restartPolicy: Never
  containers:
  - name: client-container
    image: client
    imagePullPolicy: IfNotPresent
    env:
    - name: CLIENT_ID
      value: CLIENT_ID_DUMMY
  hostNetwork: true
