apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    role: frontend
spec:
  restartPolicy: Never
  containers:
  - name: frontend-container
    image: frontend
    imagePullPolicy: Never
    env:
    - name: KVS_CLUSTER_NAME
      value: cs380d
  imagePullSecrets:
  - name: regcred
  hostNetwork: true
