apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    role: server
spec:
  restartPolicy: Never
  containers:
  - name: server-container
    image: server
    imagePullPolicy: IfNotPresent
    env:
    - name: SERVER_ID
      value: SERVER_ID_DUMMY
  hostNetwork: true
